# tests/bug_report.py

import sys
import platform
from pathlib import Path
from datetime import datetime


def generate_bug_report(
    test_name,
    error_message,
    environment=f"Chromium / {platform.system()} / {platform.release()}"
):
    """
    Takes a failed test's details and writes a formatted
    Markdown bug report to the tests/reports/ folder.
    """

    # Single timestamp used for both the filename and report content
    # e.g. 2026-03-09_16-45-01
    now = datetime.now()
    timestamp = now.strftime("%Y-%m-%d_%H-%M-%S")

    # Build the reports folder path relative to this file
    reports_dir = Path(__file__).parent / "reports"
    reports_dir.mkdir(exist_ok=True)

    filepath = reports_dir / f"bug_report_{timestamp}.md"

    # Extract just the test file from the nodeid for the reproduction steps
    # nodeid format: "tests/test_smoke.py::test_name[chromium]"
    test_file = test_name.split("::")[0]

    report = f"""# Bug Report

**Date:** {now.strftime("%Y-%m-%d %H:%M:%S")}
**Environment:** {environment}
**Status:** FAILED

---

## Test name
`{test_name}`

## Error message
```
{error_message}
```

## Steps to reproduce
1. Run: `pytest {test_file} -v`
2. Observe failure in: `{test_name}`

## Expected result
Test passes with no assertion errors.

---
*Auto-generated by bug_report.py*
"""

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"\n📋 Bug report saved: {filepath}")
    return filepath