# tests/bug_report.py

import os
from datetime import datetime

def generate_bug_report(test_name, error_message, environment="Chromium / Windows / Local file"):
    """
    Takes a failed test's details and writes a formatted
    markdown bug report to the tests/reports/ folder.
    """

    # Create a timestamp for the filename
    # e.g. 2026-03-09_16-45-01
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

    # Build the reports folder path relative to this file
    reports_dir = os.path.join(os.path.dirname(__file__), "reports")

    # Create the folder if it doesn't exist yet
    os.makedirs(reports_dir, exist_ok=True)

    # Build the full file path
    filename = f"bug_report_{timestamp}.md"
    filepath = os.path.join(reports_dir, filename)

    # Format the report content
    report = f"""# Bug Report

**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Environment:** {environment}
**Status:** FAILED

---

## Test Name
`{test_name}`

## Error Message
```
{error_message}
```

## Steps To Reproduce
1. Run the test suite: `pytest tests/ -v`
2. Observe failure in: `{test_name}`

## Expected Result
Test should pass with no assertion errors.

## Actual Result
{error_message}

---
*Auto-generated by bug_report.py*
"""

    # Write the file
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"\n📋 Bug report saved: {filepath}")
    return filepath